- name: Run Tests (EditMode)
  uses: game-ci/unity-test-runner@v4
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: .
    unityVersion: 6000.1.17f1
    testMode: EditMode
    artifactsPath: test-results/
    coverageOptions: generateAdditionalMetrics;generateHtmlReport